### PR TITLE
CI: Add VERSION label to docker images

### PR DESCRIPTION
**Pull request by glensc**

### CODE REVIEW

**Comment by nylonee** [comment]
Hmm, this PR looks good in theory, but looks like the CI/CD is failing here, I'll take a look

**Review by nylonee — APPROVED** [review]

**Comment by nylonee** [comment]
Looks like you might need to be a 'collaborator'. I've sent you an invite, once you've accepted that try re-running the docker alpha release here and let's see if it works

**Comment by glensc** [comment]
for reference, the error being unable to login to docker.io:

```
Run docker/login-action@v1
Error: Username and password required
```

- https://github.com/nylonee/watchlistarr/actions/runs/8588322583/job/23533089065?pr=117

**Comment by nylonee** [comment]
Ah after some more digging, looks like it's because you're pushing from your repository to this one.

The Github Actions Secrets page has this:
> Anyone with collaborator access to this repository can use these secrets and variables for actions. They are not passed to workflows that are triggered by a pull request from a fork.

I think this is reasonable, I certainly don't want my docker token to be used everywhere!

I can merge this PR for now, but if you need github actions to trigger in the future then it'd be better to use the nylonee/watchlistarr repository, or set up your own `DOCKERHUB_TOKEN` and `DOCKERHUB_USERNAME` (though it'll get pushed to your docker repository, at least that test will pass and you can test the docker image straight from a PR)

**Pull request merged**
